// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdfxyifofyizomypdabn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZnh5aWZvZnlpem9teXBkYWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjQ0NDQsImV4cCI6MjA3MzcwMDQ0NH0.cpe_l3qCKHa-AL0ORrkku-BXVn_VWa5OPMQ27hL4tNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});